# env
language: node_js
node_js:
  - "8"
# scripts
script:
  - yarn run build:prod
  - yarn run prepare
# config
notifications:
  email:
    on_success: never
    on_failure: always
# safelist
branches:
  only:
  - master

